name: Wishlister
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  flutter_contacts: ^1.1.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10 


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  
  adaptive_icon_background: "#81d5fc" 
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: PixelifySans
      fonts:
        - asset: assets/fonts/PixelifySans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PixelifySans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PixelifySans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PixelifySans-Bold.ttf
          weight: 700